### ISSUE TITLE
What id should we write in field "Enter Call ID"?

### ISSUE THREAD

**Issue by Hanzla-dev0** [wafaMohamed/video_call_zego_cloud_cubit#1]
What id should we write in field "Enter Call ID"?
When I enter integer value it give error invalid id...

**Comment by wafaMohamed** [comment]
Create a call ID that represents the call you want to make. It must be an alphanumeric string with 8 characters and can only contain numbers, letters, and underscores (_). For example, 'a1b2c3d4'.
